In [6]:
# ============================
# Titanic Data Preprocessing
# Beginner Friendly Version
# ============================

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# ---------------------------
# Load Dataset
# ---------------------------
titanic_data = pd.read_csv('train.csv')

print("--- Initial Data Preview ---")
print(titanic_data.head())

print("\n--- Dimensions of the Original DataFrame ---")
print("Original DataFrame dimensions:", titanic_data.shape)

# ---------------------------
# ðŸŒŸ Exercise 1: Duplicates
# ---------------------------
print("\n--- Checking for Duplicates ---")
print("Number of duplicate rows:", titanic_data.duplicated().sum())

df_cleaned = titanic_data.drop_duplicates()
print("Dimensions after removing duplicates:", df_cleaned.shape)

# ---------------------------
# ðŸŒŸ Exercise 2: Missing Values
# ---------------------------
print("\n--- Identifying Missing Values ---")
missing_values_count = df_cleaned.isnull().sum()
columns_with_missing_data = missing_values_count[missing_values_count > 0]
print(columns_with_missing_data)

# Drop 'Cabin' (too many missing values)
df_cleaned.drop('Cabin', axis=1, inplace=True)
print("\nDropped 'Cabin' column.")

# Fill 'Age' with median (using SimpleImputer)
imputer_age = SimpleImputer(strategy='median')
df_cleaned['Age'] = imputer_age.fit_transform(df_cleaned[['Age']]).ravel()
print(f"Filled missing Age with median: {imputer_age.statistics_[0]}")

# Fill 'Embarked' with most frequent value
imputer_embarked = SimpleImputer(strategy='most_frequent')
df_cleaned['Embarked'] = imputer_embarked.fit_transform(df_cleaned[['Embarked']]).ravel()
print("Filled missing Embarked with most frequent value.")

print("\nMissing values after cleaning:")
print(df_cleaned.isnull().sum())

# ---------------------------
# ðŸŒŸ Exercise 3: Feature Engineering
# ---------------------------
print("\n--- Feature Engineering ---")

# Family Size
df_cleaned['FamilySize'] = df_cleaned['SibSp'] + df_cleaned['Parch'] + 1

# Title from Name
df_cleaned['Title'] = df_cleaned['Name'].str.extract(' ([A-Za-z]+)\.')

# Encode categorical variables
df_cleaned = pd.get_dummies(df_cleaned, columns=['Sex','Embarked','Title'], drop_first=True)

print("Added FamilySize and Title features.")

# ---------------------------
# ðŸŒŸ Exercise 4: Outliers
# ---------------------------
print("\n--- Handling Outliers ---")

fare_cap = df_cleaned['Fare'].quantile(0.98)
df_cleaned['Fare'] = np.where(df_cleaned['Fare'] > fare_cap, fare_cap, df_cleaned['Fare'])
print(f"Capped Fare at 98th percentile: {fare_cap}")

# ---------------------------
# ðŸŒŸ Exercise 5: Scaling
# ---------------------------
print("\n--- Scaling Features ---")

scaler_standard = StandardScaler()
scaler_minmax = MinMaxScaler()

df_cleaned['Age_scaled'] = scaler_standard.fit_transform(df_cleaned[['Age']]).ravel()
df_cleaned['Fare_scaled'] = scaler_minmax.fit_transform(df_cleaned[['Fare']]).ravel()

print("Created Age_scaled (StandardScaler) and Fare_scaled (MinMaxScaler).")

# ---------------------------
# ðŸŒŸ Exercise 6: Final Encoding & Cleanup
# ---------------------------
print("\n--- Final Encoding & Cleanup ---")

df_cleaned = df_cleaned.drop(columns=['PassengerId','Name','Ticket'])
print("Dropped PassengerId, Name, Ticket.")

# ---------------------------
# ðŸŒŸ Exercise 7: Age Groups
# ---------------------------
print("\n--- Age Groups ---")

bins = [0, 12, 18, 60, 100]
labels = ['Child','Teen','Adult','Senior']
df_cleaned['AgeGroup'] = pd.cut(df_cleaned['Age'], bins=bins, labels=labels)

df_cleaned = pd.get_dummies(df_cleaned, columns=['AgeGroup'], drop_first=True)
print("Created AgeGroup categories.")

# ---------------------------
# Final Check
# ---------------------------
print("\n--- Final Dataset Info ---")
print("Final dataset shape:", df_cleaned.shape)
print(df_cleaned.head())

--- Initial Data Preview ---
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

--- Dimensions of the Original DataFrame ---
Original DataFrame dimensions: (891, 12)

--- Checking for Duplicates ---
Number of duplicate rows: 0
Dimensions after removing duplicates: (891, 12)

--- Identifying Missing Values ---
Age         177
Cabin       687
Embarked      2
dtype: int64

Dropped 'Cabin' column.
Filled missing Age with median: 28.0
Filled missing Embarked with most frequent value.

Missing values after cleaning:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

--- Feature Engineering ---
Added FamilySize and Title features.

--- Handling Outliers ---
Capped Fare at 98th percentile: 211.3375

--- Scaling Features ---
Created Age_scaled (StandardScaler) and Fare_scaled (MinMaxScaler).

--- Final Encoding & Cleanup ---
Dropped PassengerId, Name, Ticket.

--- Age Groups ---
Created AgeGroup categories.

--- Final Dataset Info ---
Final dataset shape: (891, 31)
   Survived  Pclass   Age  SibSp  Parch     Fare  FamilySize  Sex_male  \
0         0       3  22.0      1      0   7.2500           2      True
1         1       1  38.0      1      0  71.2833           2     False
2         1       3  26.0      0      0   7.9250           1     False
3         1       1  35.0      1      0  53.1000           2     False
4         0       3  35.0      0      0   8.0500           1      True

   Embarked_Q  Embarked_S  ...  Title_Mr  Title_Mrs  Title_Ms  Title_Rev  \
0       False        True  ...      True      False     False      False
1       False       False  ...     False       True     False      False
2       False        True  ...     False      False     False      False
3       False        True  ...     False       True     False      False
4       False        True  ...      True      False     False      False

   Title_Sir  Age_scaled  Fare_scaled  AgeGroup_Teen  AgeGroup_Adult  \
0      False   -0.565736     0.034305          False            True
1      False    0.663861     0.337296          False            True
2      False   -0.258337     0.037499          False            True
3      False    0.433312     0.251257          False            True
4      False    0.433312     0.038091          False            True

   AgeGroup_Senior
0            False
1            False
2            False
3            False
4            False

[5 rows x 31 columns]

<>:65: SyntaxWarning: invalid escape sequence '\.'
<>:65: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipython-input-2000312562.py:65: SyntaxWarning: invalid escape sequence '\.'
  df_cleaned['Title'] = df_cleaned['Name'].str.extract(' ([A-Za-z]+)\.')